# .github/workflows/release.yml

name: Publish to Rubygems

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    steps:
      # Create release
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          command: github-release
          package-name: logstasher
          bump-minor-pre-major: true
          # Path to our version file to increment
          version-file: "lib/logstasher/version.rb"
          token: "${{secrets.GITHUB_TOKEN}}"
      # Checkout code if release was created
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      # Setup ruby if a release was created
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
        if: ${{ steps.release.outputs.release_created }}
      # Bundle install
      - run: bundle install
        if: ${{ steps.release.outputs.release_created }}
      # Publish to GPR
      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
        if: ${{ steps.release.outputs.release_created }}
      # Publish gem to Rubygems
      - name: Publish to Rubygems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          # Make sure to update the secret name
          # if yours isn't named RUBYGEMS_AUTH_TOKEN
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        if: ${{ steps.release.outputs.release_created }}
